/* The SmartHomeProject.org
 * Copyright (C) 2015  Ognyan Tonchev <otonchev at gmail.com >
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This is a plugin for storing data generated by another plugin into a
 * MySQL database.
 *
 * This is the configuration specification for this plugin:
 *
 * Config spec:
 *
 * Properties inherited from baseplugin:
 *
 * interval=<integer>
 *
 * Properties for this plugin(main properties):
 *
 * database=<string>
 * username=<string>
 * password=<string>
 * table=<string>
 *
 * Additional properties in the second configuration(normally generated at
 * runtime):
 *
 * <Field_Name>=<Value_of_a_certain_type>
 */

#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include <mysql.h>

#include "../shp-data.h"
#include "../shp-pad.h"
#include "../shp-plugin-factory.h"
#include "shp-mysql.h"

#define NAME "mysql"

#define DEFAULT_DATABASE NULL
#define DEFAULT_USERNAME NULL
#define DEFAULT_PASSWORD NULL
#define DEFAULT_TABLE NULL

enum
{
  PROP_0,
  PROP_DATABASE,
  PROP_USERNAME,
  PROP_PASSWORD,
  PROP_TABLE,
  PROP_LAST
};

static void shp_mysql_finalize (GObject * object);

static void shp_mysql_data_received (ShpPlugin * plugin, ShpPad * pad,
    ShpData * data);
static gboolean shp_mysql_start (ShpPlugin * plugin);
static void shp_mysql_stop (ShpPlugin * plugin);

static void shp_mysql_get_property (GObject * object, guint propid,
    GValue * value, GParamSpec * pspec);
static void shp_mysql_set_property (GObject * object, guint propid,
    const GValue * value, GParamSpec * pspec);

G_DEFINE_TYPE (ShpMysql, shp_mysql, SHP_PLUGIN_TYPE);

static void
shp_mysql_class_init (ShpMysqlClass * klass)
{
  GObjectClass *gobject_class;

  gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->finalize = shp_mysql_finalize;
  gobject_class->set_property = shp_mysql_set_property;
  gobject_class->get_property = shp_mysql_get_property;

  SHP_PLUGIN_CLASS (klass)->data_received = shp_mysql_data_received;

  g_object_class_install_property (gobject_class, PROP_DATABASE,
      g_param_spec_string ("database", "Database name", "Database name",
          DEFAULT_DATABASE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

  g_object_class_install_property (gobject_class, PROP_USERNAME,
      g_param_spec_string ("username", "Database user name",
          "Database user name", DEFAULT_USERNAME, G_PARAM_READWRITE |
          G_PARAM_STATIC_STRINGS));

  g_object_class_install_property (gobject_class, PROP_PASSWORD,
      g_param_spec_string ("password", "Database password", "Database password",
          DEFAULT_PASSWORD, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

  g_object_class_install_property (gobject_class, PROP_TABLE,
      g_param_spec_string ("table", "Table name", "Table name",
          DEFAULT_TABLE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

  SHP_PLUGIN_CLASS (klass)->start = shp_mysql_start;
  SHP_PLUGIN_CLASS (klass)->stop = shp_mysql_stop;
}

static void
shp_mysql_init (ShpMysql * self)
{
  g_mutex_init (&self->mutex);
  self->database = g_strdup (DEFAULT_DATABASE);
  self->username = g_strdup (DEFAULT_USERNAME);
  self->password = g_strdup (DEFAULT_PASSWORD);
  self->table = g_strdup (DEFAULT_TABLE);
}

static void
shp_mysql_finalize (GObject * object)
{
  ShpMysql *self = SHP_MYSQL (object);

  g_mutex_clear (&self->mutex);
  g_free (self->database);
  g_free (self->username);
  g_free (self->password);
  g_free (self->table);
}

static void
shp_mysql_get_property (GObject * object, guint propid, GValue * value,
    GParamSpec * pspec)
{
  ShpMysql *self = SHP_MYSQL (object);

  switch (propid) {
    case PROP_DATABASE:
      g_value_take_string (value, g_strdup (self->database));
      break;
    case PROP_USERNAME:
      g_value_take_string (value, g_strdup (self->username));
      break;
    case PROP_PASSWORD:
      g_value_take_string (value, g_strdup (self->password));
      break;
    case PROP_TABLE:
      g_value_take_string (value, g_strdup (self->table));
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, propid, pspec);
  }
}

static void
shp_mysql_set_property (GObject * object, guint propid,
    const GValue * value, GParamSpec * pspec)
{
  ShpMysql *self = SHP_MYSQL (object);

  switch (propid) {
    case PROP_DATABASE:
      g_free (self->database);
      self->database = g_strdup (g_value_get_string (value));
      break;
    case PROP_USERNAME:
      g_free (self->username);
      self->username = g_strdup (g_value_get_string (value));
      break;
    case PROP_PASSWORD:
      g_free (self->password);
      self->password = g_strdup (g_value_get_string (value));
      break;
    case PROP_TABLE:
      g_free (self->table);
      self->table = g_strdup (g_value_get_string (value));
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, propid, pspec);
  }
}

static gboolean
shp_mysql_start (ShpPlugin * plugin)
{
  return TRUE;
}

static void
shp_mysql_stop (ShpPlugin * plugin)
{
}

typedef struct {
  GString *spec;
  GString *values;
  guint num_params;
} _ShpMysqlData;

static void
configuration_cb (const gchar * name, const GValue * value, gpointer user_data)
{
  _ShpMysqlData *data = user_data;

  if (data->num_params > 0) {
    g_string_append (data->spec, ", ");
    g_string_append (data->values, ", ");
  }

  g_string_append (data->spec, name);

  if (G_VALUE_TYPE (value) == G_TYPE_STRING) {
    g_string_append (data->values, "\"");
    g_string_append (data->values, g_value_get_string (value));
    g_string_append (data->values, "\"");
  } else if (G_VALUE_TYPE (value) == G_TYPE_DOUBLE) {
    g_string_append_printf (data->values, "%f", g_value_get_double (value));
  } else if (G_VALUE_TYPE (value) == G_TYPE_FLOAT) {
    g_string_append_printf (data->values, "%f", g_value_get_float (value));
  } else if (G_VALUE_TYPE (value) == G_TYPE_INT) {
    g_string_append_printf (data->values, "%d", g_value_get_int (value));
  }

  data->num_params++;
}

static void
shp_mysql_data_received (ShpPlugin * plugin, ShpPad * pad, ShpData * data)
{
  MYSQL *con;
  const gchar *username;
  const gchar *password;
  const gchar *database;
  const gchar *table;
  gchar *query;
  gchar *query_spec;
  gchar *query_values;
  _ShpMysqlData *mysql_data;
  ShpMysql *self = SHP_MYSQL (plugin);

  g_return_val_if_fail (data != NULL, FALSE);

  /* chain up to parent first */
  if (!shp_plugin_check (plugin)) {
    return;
  }

  if (data == NULL || shp_data_size (data) == 0) {
    g_warning ("missing or empty data");
    return;
  }

  if (self->username == NULL) {
    g_warning ("incomplete configuration, 'username' not set");
    return;
  }
  username = self->username;

  if (self->password == NULL) {
    g_warning ("incomplete configuration, 'password' not set");
    return;
  }
  password = self->password;

  if (self->database == NULL) {
    g_warning ("incomplete configuration, 'database' not set");
    return;
  }
  database = self->database;

  if (self->table == NULL) {
    g_warning ("incomplete configuration, 'table' not set");
    return;
  }
  table = self->table;

  con = mysql_init (NULL);
  if (con == NULL) {
    g_warning ("unable to init MySQL");
    return;
  }

  if (mysql_real_connect (con, "localhost", username, password,  NULL, 0, NULL,
          0) == NULL) {
    g_warning ("unable to connect to MySQL database");
    return;
  }

  query = g_strdup_printf ("USE %s", database);

  if (mysql_query (con, query)) {
    g_warning ("unable to execute: %s", query);
    mysql_close (con);
    g_free (query);
    return;
  }
  g_free (query);

  /* create query */
  mysql_data = g_new0 (_ShpMysqlData, 1);
  mysql_data->spec = g_string_new ("");
  mysql_data->values = g_string_new ("");
  mysql_data->num_params = 0;
  shp_data_foreach (data, configuration_cb, mysql_data);
  query_spec = g_string_free (mysql_data->spec, FALSE);
  query_values = g_string_free (mysql_data->values, FALSE);
  g_free (mysql_data);

  query = g_strdup_printf ("INSERT INTO %s (%s) VALUES (%s)", table, query_spec,
      query_values);
  g_debug ("query: %s", query);

  if (mysql_query (con, query)) {
    g_warning ("unable to execute: %s", query);
    mysql_close (con);
    g_free (query);
    return;
  }
  g_free (query);

  mysql_close (con);

  return;
}

void
shp_plugin_register (void)
{
  shp_plugin_factory_register (NAME, SHP_MYSQL_TYPE);
}
